CustomerClient/CustomerClient/Models/Entity/Customer.cs
using CustomerClient.Models.Global;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Security.Cryptography;
using System.Text;
using System.Web;

namespace CustomerClient.Models.Entity
{
    public class Customer
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public int Status { get; set; }
        public string CMND { get; set; }
        public string PhoneNumber { get; set; }
        public string Avatar { get; set; }
        public int? Rate { get; set; }
        public DateTime Created { get; set; }
        public IEnumerable<Auction> Auctions { get; set; }
        public IEnumerable<Customer> GetAll()
        {
            IEnumerable<Customer> data;
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("Customer").Result;
            data = response.Content.ReadAsAsync<IEnumerable<Customer>>().Result;
            return data;

        }

        public Customer GetById(int id)
        {
            Customer data;
            HttpResponseMessage response = GlobalVariables.WebApiClient.GetAsync("Customer/" + id).Result;
            data = response.Content.ReadAsAsync<Customer>().Result;
            return data;
        }

        public Customer Edit(Customer c)
        {
            Customer data;
            HttpResponseMessage response = GlobalVariables.WebApiClient.PutAsJsonAsync("Customer", c).Result;
            data = response.Content.ReadAsAsync<Customer>().Result;
            return data;
        }

        public Message AddNew(Customer c)
        {
            Message data;
            HttpResponseMessage response = GlobalVariables.WebApiClient.PostAsJsonAsync("Customer", c).Result;
            data = response.Content.ReadAsAsync<Message>().Result;
            return data;
        }

        public Customer GetCustById(int id)
        {
            var customer = GetById(id);
            Auction au = new Auction();
            var dataAu = au.GetListByCustomer(id);
            customer.Auctions = dataAu;
            return customer;
        }


        //ma hoa pass
        public string GETSHA(string str)
        {
            /*MD5 md5 = new MD5CryptoServiceProvider();*/
            SHA512 sha = new SHA512CryptoServiceProvider();
            byte[] fromData = Encoding.UTF8.GetBytes(str);
            byte[] targetData = sha.ComputeHash(fromData);
            string byte2String = null;

            for (int i = 0; i < targetData.Length; i++)
            {
                byte2String += targetData[i].ToString("x2");

            }
            return byte2String;
        }


    }
}

CustomerClient/CustomerClient/Controllers/CustomerController.cs
using CustomerClient.Models.Entity;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CustomerClient.Controllers
{
    public class CustomerController : Controller
    {
        private Customer customer;
        private Order order;
        private Auction auction;
        public CustomerController()
        {
            customer = new Customer();
            order = new Order();
            auction = new Auction();
        }
        public ActionResult Index(int id)
        {
            if (Session["loginCustomer"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            var dataaucByCusId = auction.GetListByCustId(id);
            var data = order.GetOdByCustID(id).OrderBy(x => x.Created);
            ViewBag.Order0 = data.Where(x => x.status == 0);
            ViewBag.AuctionAll = dataaucByCusId.OrderByDescending(x=>x.Created);
            ViewBag.StCount0 = dataaucByCusId.Where(x => x.Status == 0).Count();
            ViewBag.StCount1 = dataaucByCusId.Where(x => x.Status == 1).Count();
            ViewBag.StCount2 = dataaucByCusId.Where(x => x.Status == 2).Count();
            ViewBag.StCount3 = dataaucByCusId.Where(x => x.Status == 3).Count();

            return View();
        }

        public ActionResult PersonalProfile(int id)
        {
            ViewBag.profile = customer.GetCustById(id);
            return PartialView("_PersonalProfile");
        }

        public ActionResult MyOrder(int id,int? page)
        {
            if (Session["loginCustomer"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            int _page = page ?? 1;
            int _pageSize = 20;
            var data = order.GetOdByCustID(id).OrderBy(x => x.Created);
            ViewBag.OrderAll = data.ToPagedList(_page, _pageSize);
            ViewBag.Order0 = data.Where(x => x.status == 0).ToPagedList(_page, _pageSize);
            ViewBag.Order1 = data.Where(x => x.status == 1).ToPagedList(_page, _pageSize);
            ViewBag.Order2 = data.Where(x => x.status == 2).ToPagedList(_page, _pageSize);
            ViewBag.Order3 = data.Where(x => x.status == 3).ToPagedList(_page, _pageSize);
            ViewBag.Order4 = data.Where(x => x.status == 4).ToPagedList(_page, _pageSize);

            ViewBag.StCount0 = data.Where(x => x.status == 0).Count();
            ViewBag.StCount1 = data.Where(x => x.status == 1).Count();
            ViewBag.StCount2 = data.Where(x => x.status == 2).Count();
            ViewBag.StCount3 = data.Where(x => x.status == 3).Count();


            return View();
        }

        public ActionResult UpdateOrder(int id)
        {
            ViewBag.OrderData = order.GetOrderById(id);
            return PartialView("_UpdateOrder");
        }

        [HttpPost]
        public ActionResult UpdateOrder(FormCollection form)
        {
            Order data = order.GetById(int.Parse(form["id"]));
            try
            {
                data.Email = form["email"];
                data.Receiver = form["receiver"];
                data.Phone = form["phone"];
                data.Note = form["note"];
                data.Payment = int.Parse(form["payment"]);
                data.status = 1;
                order.Edit(data);
                return RedirectToAction("MyOrder", new { id = data.CustomerID });
            }
            catch { }
            return RedirectToAction("MyOrder", new { id = data.CustomerID });

        }

      

    }
}

CustomerClient/CustomerClient/Controllers/ProductAuctionController.cs
using CustomerClient.Common;
using CustomerClient.Models.Entity;
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CustomerClient.Controllers
{
    public class ProductAuctionController : Controller
    {
        ProductAuction productAuction;
        Auction auction;
        ProAuParameter proAuParameter;
        Brand brand;
        private Order order;
        private Customer customer;
        private Category category;
        public ProductAuctionController()
        {
            productAuction  = new ProductAuction();
            auction         = new Auction();
            proAuParameter  = new ProAuParameter();
            brand           = new Brand();
            order           = new Order();
            customer        = new Customer();
            category        = new Category();
        }
        // GET: ProductAuction
        public ActionResult GetAll(int? page,int? sort_name,int? sort_pro)
        {
            int _page = page ?? 1;
            int _pageSize = 20;
            int _sort_name = sort_name ?? 0;
            int _sort_pro = sort_pro ?? 0;
            var dataAllSt1 = productAuction.GetAllProAuc();
           
            switch (_sort_name)
            {
                case 0:
                    ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 1 || x.Status == 0).OrderByDescending(x => x.Status).ToPagedList(_page, _pageSize);
                    break;
                case 1:
                    switch(sort_pro)
                    {
                        case 0:
                            ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 1 || x.Status == 0).OrderByDescending(x => x.Status).ToPagedList(_page, _pageSize);
                            break;
                        case 1:
                            ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 1).OrderByDescending(x => x.Status).ToPagedList(_page, _pageSize);
                            break;
                        case 2:
                            ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 0).OrderByDescending(x => x.Status).ToPagedList(_page, _pageSize);
                            break;
                    }
                    break;                    
                case 2:
                    switch (sort_pro)
                    {
                        case 0:
                            ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 1 || x.Status == 0).OrderByDescending(x => x.ProName).ToPagedList(_page, _pageSize);
                            break;
                        case 1:
                            ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 1).OrderByDescending(x => x.ProName).ToPagedList(_page, _pageSize);
                            break;
                        case 2:
                            ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 0).OrderByDescending(x => x.ProName).ToPagedList(_page, _pageSize);
                            break;
                    }
                   
                    break;
                case 3:
                    switch (sort_pro)
                    {
                        case 0:
                            ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 1 || x.Status == 0).OrderByDescending(x => x.EndDateTime).ToPagedList(_page, _pageSize);
                            break;
                        case 1:
                            ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 1).OrderByDescending(x => x.EndDateTime).ToPagedList(_page, _pageSize);
                            break;
                        case 2:
                            ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 0).OrderByDescending(x => x.EndDateTime).ToPagedList(_page, _pageSize);
                            break;
                    }
                 
                    break;
                case 4:
                    switch (sort_pro)
                    {
                        case 0:
                            ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 1 || x.Status == 0).OrderByDescending(x => x.StartDateTime).ToPagedList(_page, _pageSize);
                            break;
                        case 1:
                            ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 1).OrderByDescending(x => x.StartDateTime).ToPagedList(_page, _pageSize);
                            break;
                        case 2:
                            ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 0).OrderByDescending(x => x.StartDateTime).ToPagedList(_page, _pageSize);
                            break;
                    }

                    break;
                default:
                    ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 1 || x.Status == 0).OrderByDescending(x => x.Status).ToPagedList(_page, _pageSize);
                    break;
            }




            var dataCate = category.GetAll().Where(x => x.Status == 1);
            ViewBag.Category = dataCate;

            ViewBag.ProTake3EndTm = productAuction.GetProByEndTimeDESC();
            return View();
        }

        //Get pro by Category
        public ActionResult GetProByCate(int cateid,int? page,int? sort_name,int? sort_pro)
        {
            int _page = page ?? 1;
            int _pageSize = 20;
            int _sort_name = sort_name ?? 0;
            int _sort_pro = sort_pro ?? 0;


            var dataAllSt1 = productAuction.GetAllProAuc().Where(x=>x.CategoryID == cateid).Where(x => x.Status == 1 || x.Status == 0).OrderByDescending(x => x.Status);
            switch (_sort_name)
            {
                case 0:
                    ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 1 || x.Status == 0).OrderByDescending(x => x.Status).ToPagedList(_page, _pageSize);
                    break;
                case 1:
                    switch (sort_pro)
                    {
                        case 0:
                            ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 1 || x.Status == 0).OrderByDescending(x => x.Status).ToPagedList(_page, _pageSize);
                            break;
                        case 1:
                            ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 1).OrderByDescending(x => x.Status).ToPagedList(_page, _pageSize);
                            break;
                        case 2:
                            ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 0).OrderByDescending(x => x.Status).ToPagedList(_page, _pageSize);
                            break;
                    }
                    break;
                case 2:
                    switch (sort_pro)
                    {
                        case 0:
                            ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 1 || x.Status == 0).OrderByDescending(x => x.ProName).ToPagedList(_page, _pageSize);
                            break;
                        case 1:
                            ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 1).OrderByDescending(x => x.ProName).ToPagedList(_page, _pageSize);
                            break;
                        case 2:
                            ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 0).OrderByDescending(x => x.ProName).ToPagedList(_page, _pageSize);
                            break;
                    }

                    break;
                case 3:
                    switch (sort_pro)
                    {
                        case 0:
                            ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 1 || x.Status == 0).OrderByDescending(x => x.EndDateTime).ToPagedList(_page, _pageSize);
                            break;
                        case 1:
                            ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 1).OrderByDescending(x => x.EndDateTime).ToPagedList(_page, _pageSize);
                            break;
                        case 2:
                            ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 0).OrderByDescending(x => x.EndDateTime).ToPagedList(_page, _pageSize);
                            break;
                    }

                    break;
                case 4:
                    switch (sort_pro)
                    {
                        case 0:
                            ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 1 || x.Status == 0).OrderByDescending(x => x.StartDateTime).ToPagedList(_page, _pageSize);
                            break;
                        case 1:
                            ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 1).OrderByDescending(x => x.StartDateTime).ToPagedList(_page, _pageSize);
                            break;
                        case 2:
                            ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 0).OrderByDescending(x => x.StartDateTime).ToPagedList(_page, _pageSize);
                            break;
                    }

                    break;
                default:
                    ViewBag.DataAllSt = dataAllSt1.Where(x => x.Status == 1 || x.Status == 0).OrderByDescending(x => x.Status).ToPagedList(_page, _pageSize);
                    break;
            }

            ViewBag.CateId = cateid;
            ViewBag.ProTake3EndTm = productAuction.GetProByEndTimeDESC();
            return View();
        }
        public ActionResult Details(int id)
        {
            var data = productAuction.GetById(id);
            ViewBag.DetailProAuction = data;
            ViewBag.Brand = brand.GetById(data.BrandID);
            var dataAuction = auction.GetByProduct(id);
            if(dataAuction.Count()==0)
            {
                ViewBag.ProAuction = null;
            }
            else
            {

CustomerClient/CustomerClient/Views/Customer/Index.cshtml
@using CustomerClient.Models.Entity
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}

<div class="cart-sidebar-area">
    <div class="top-content">
        <a href="index.html" class="logo">
            <img src="~/Assets/assets/images/logo/logo2.png" alt="logo">
        </a>
        <span class="side-sidebar-close-btn"><i class="fas fa-times"></i></span>
    </div>
    <div class="bottom-content">

    </div>
</div>

<div class="hero-section style-2">
    <div class="container">
        <ul class="breadcrumb">
        </ul>
    </div>
    <div class="bg_img hero-bg bottom_center" data-background="https://localhost:44300/Assets/assets/images/banner/hero-bg.png" style="        background-image: url(&quot;https://localhost:44300/Assets/assets/images/banner/hero-bg.png&quot;);"></div>
</div>

<section class="dashboard-section padding-bottom mt--240 mt-lg--440 pos-rel">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-10 col-md-7 col-lg-4">
                <div class="dashboard-widget mb-30 mb-lg-0 sticky-menu">
                    <div class="user">
                        <div class="thumb-area">
                            <div class="thumb">
                                <img src="~/Assets/assets/images/dashboard/user.png" alt="user">
                            </div>
                            <label for="profile-pic" class="profile-pic-edit"><i class="flaticon-pencil"></i></label>
                            <input type="file" id="profile-pic" class="d-none">
                        </div>
                        <div class="content">
                            <h5 class="title"><a href="#0">@((Session["loginCustomer"] as Customer).FullName)</a></h5>
                            <span class="username">@((Session["loginCustomer"] as Customer).Email)</span>
                        </div>
                    </div>
                    <ul class="dashboard-menu">
                        <li>
                            <a href="javascript:void(0)" onclick="Dasboarh()"><i class="flaticon-dashboard"></i>Dashboard</a>
                        </li>
                        <li>
                            <a href="javascript:void(0)" onclick="Profile(@((Session["loginCustomer"] as Customer).ID))"><i class="flaticon-settings"></i>Personal Profile </a>
                        </li>
                      
                        <li>
                            <a href="@Url.Action("MyOrder","Customer",new {id = (Session["loginCustomer"] as Customer).ID })"><i class="flaticon-shake-hand"></i>My Order's</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Logout","Home")"><i class="fas fa-sign-out-alt" style="font-weight:0 !important;"></i>Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class=" col-lg-8" id="content-saleman">
                <div class="dashboard-widget mb-40">

                </div>
                <div class="dashboard-widget">
                    <h5 class="title mb-10">Dashboard</h5>
                    <div class="dashboard-purchasing-tabs">
                        <ul class="nav-tabs nav">
                            <li>
                                <a href="#current" class="active" data-toggle="tab">Auction</a>
                            </li>
                            <li>
                                <a href="#pending" data-toggle="tab">My Order</a>
                            </li>

                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane show active fade" id="current">
                                <table class="purchasing-table">
                                    <thead>
                                        <tr>
                                            <th>Item</th>
                                            <th>Highest Bid</th>
                                            <th>Bid Price</th>
                                            <th>Lowest Bid</th>
                                            <th>Date time</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in ViewBag.AuctionAll)
                                        {
                                            <tr>
                                                @{
                                                    Auction auction = new Auction();
                                                    var stClass = "";
                                                    var stValue = "";
                                                    if (item.Status != null)
                                                    {
                                                        stClass = auction.AuctionStatusClass(item.Status);
                                                        stValue = auction.AuctionStatus(item.Status);
                                                    }
                                                    else
                                                    {
                                                        stClass = "badge badge-primary";
                                                        stValue = "waiting";
                                                    }



                                                    var pricehighest = auction.AucPriceDESC(item.ProAutionID);
                                                }
                                                <td data-purchase="item"><a style="color:#000" href="@Url.Action("Details","ProductAuction",new { id = item.ProAutionID })">@item.ProductAuction.ID</a> </td>
                                                <td data-purchase="bid price">$@Convert.ToDecimal(pricehighest.Price).ToString("#,##0.0")</td>
                                                <td data-purchase="highest bid">$@Convert.ToDecimal(item.Price).ToString("#,##0.0")</td>
                                                <td data-purchase="lowest bid"><p class="@stClass">@stValue</p></td>

                                                <td data-purchase="expires">@item.Created</td>
                                            </tr>
                                        }


                                    </tbody>
                                </table>
                            </div>
                            <div class="tab-pane show fade" id="pending">
                                <table class="purchasing-table">
                                    <thead>
                                        <tr>
                                            <th>Orders code</th>
                                            <th>Product Auction</th>
                                            <th>Total Price</th>
                                            <th>Status</th>
                                           

                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var order in ViewBag.Order0)
                                        {
                                        <tr>
                                            @{
                                                Order od = new Order();
                                                var st_value = od.OrderSt(order.status);
                                                var st_class = od.OrderStClass(order.status);
                                            }
                                            <td>@order.ID</td>
                                            <td>@order.Auction.ProductAuction.ID</td>
                                            <td>$@Convert.ToDecimal(order.TotalPrice).ToString("#,##0.0")</td>
                                            <td><span class="@st_class">@st_value</span></td>
                                            
                                        </tr>
                                        }

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
             
            </div>
        </div>
    </div>
</section>

@section scripts {
    <script>

         $(function () {
                    var sss = '@TempData["Success"]';
                    var err = '@TempData["Errors"]';
                    console.log(sss);
             if (sss != '') {
                 alert(sss);
                    swal(sss, "Hãy xác nhận để tiếp tục!", "success");
                    }
             if (err != '') {
                 alert(err);
                    swal(err, "...and here's the text!");
             }

         })
        function MyBils(id) {
            $.ajax({
                type: 'GET',
                url: 'Home/MyBids/' + id,
                success: function (res) {
                    $("#content-saleman").html(res);
                }
            })
        }
        function Profile(id) {
            $.ajax({
                type: 'GET',
                url: '../PersonalProfile/' + id,
                success: function (res) {
                    $("#content-saleman").html(res);
                }
            })
        }
        function Dasboarh() {
            $.ajax({
                type: 'GET',
                url: '@Url.Action("Index","Home")',
                success: function () {
                    location.reload();
                }
            })
        }
    </script>
}

CustomerClient/CustomerClient/Views/Customer/UpdateOrder.cshtml
@{
    ViewBag.Title = "UpdateOrder";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}
<div class="hero-section">
    <div class="container">
        <ul class="breadcrumb">
            <li>
                <a href="index.html">Home</a>
            </li>
            <li>
                <span>Contact Us</span>
            </li>
        </ul>
    </div>
    <div class="bg_img hero-bg bottom_center" data-background="https://localhost:44376/Assets/assets/images/banner/hero-bg.png" style="background-image: url(&quot;https://localhost:44376/Assets/assets/images/banner/hero-bg.png&quot;);"></div>
</div>
<section class="contact-section padding-bottom">
    <div class="container">
        <div class="contact-wrapper padding-top padding-bottom mt--100 mt-lg--440" style="padding-right:40px;">
            <div class="section-header">
                <h5 class="cate">Con</h5>
                <h2 class="title">get in touch</h2>
                <p>We'd love to hear from you! Let us know how we can help.</p>
            </div>
            
                <div class="row">
                    <div class="col-12">
                        <div class="dash-pro-item mb-30 dashboard-widget">
                            <div class="header">
                                <h4 class="title">Personal Details</h4>
                              
                            </div>
                            <ul class="dash-pro-body">
                                <li>
                                    <div class="info-name">Name</div>
                                    <div class="info-value">Albert Owens</div>
                                </li>
                                <li>
                                    <div class="info-name">Date of Birth</div>
                                    <div class="info-value">15-03-1974</div>
                                </li>
                                <li>
                                    <div class="info-name">Address</div>
                                    <div class="info-value">8198 Fieldstone Dr.La Crosse, WI 54601</div>
                                </li>
                            </ul>
                        </div>
                    </div>
                   
                </div>
           
            <div class="row">
                <div class="col-xl-8 col-lg-7">
                    @using (Html.BeginForm("UpdateOrder", "Customer", FormMethod.Post, new { enctype = "multipart/form-data", @id = "formAdd", @Class = "contact-form" }))
                    {

                        <div class="form-group">
                            <label for="name"><i class="far fa-user"></i></label>
                            <input type="text" placeholder="Your Name" name="name" id="name">
                        </div>

                        <div class="form-group">
                            <label>Mã Đơn Hàng:</label>
                            <input type="text" readonly="" name="id" class="form-control" value="@ViewBag.OrderData.ID" placeholder="Enter Receiver">
                        </div>
                        <div class="form-group">
                            <label>Người nhận:</label>
                            <input type="text" name="receiver" class="form-control" placeholder="Enter Receiver">
                        </div>
                        <div class="form-group">
                            <label>Email:</label>
                            <input type="text" name="email" class="form-control" placeholder="Enter Email">
                        </div>
                        <div class="form-group">
                            <label>Số điện thoại nhận hàng:</label>
                            <input type="number" name="phone" class="form-control" placeholder="Enter Phone">
                        </div>
                        <div class="form-group">
                            <label>Ghi chú:</label>
                            <textarea name="note" placeholder="Your notes"></textarea>
                        </div>
                        <div class="form-group">
                            <label>Hình thức thanh toán:</label>
                            <select name="payment" class="form-control">
                                <option value="1">Giao Hàng Thanh Toán</option>
                                <option value="2">Online</option>
                            </select>
                        </div>



                        <div class="form-group text-center mb-0">
                            <button type="submit" class="custom-button">Send Order</button>
                        </div>
                    }
                </div>
                <div class="col-xl-4 col-lg-5 d-lg-block d-none">
                    
                </div>
            </div>
        </div>
    </div>
</section>